language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mongodb

before_script:
 - composer self-update
 - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 - echo 'extension = mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install --dev -o -n
 - php artisan migrate:install --env="testing"

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit

