language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mongodb

before_script:
 - composer self-update
 - php -i | grep 'Mongo'
 - composer install --dev -o -n
 - php artisan migrate:install --env="testing"

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit

